// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.0--rc1
// source: gocalcharger.proto

package gocalcharger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GocalChargerServerClient is the client API for GocalChargerServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GocalChargerServerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (GocalChargerServer_DownloadFileClient, error)
}

type gocalChargerServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGocalChargerServerClient(cc grpc.ClientConnInterface) GocalChargerServerClient {
	return &gocalChargerServerClient{cc}
}

func (c *gocalChargerServerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/gocalcharger.srv.GocalChargerServer/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gocalChargerServerClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (GocalChargerServer_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &GocalChargerServer_ServiceDesc.Streams[0], "/gocalcharger.srv.GocalChargerServer/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gocalChargerServerDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GocalChargerServer_DownloadFileClient interface {
	Recv() (*DownloadFileReply, error)
	grpc.ClientStream
}

type gocalChargerServerDownloadFileClient struct {
	grpc.ClientStream
}

func (x *gocalChargerServerDownloadFileClient) Recv() (*DownloadFileReply, error) {
	m := new(DownloadFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GocalChargerServerServer is the server API for GocalChargerServer service.
// All implementations must embed UnimplementedGocalChargerServerServer
// for forward compatibility
type GocalChargerServerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	DownloadFile(*DownloadFileRequest, GocalChargerServer_DownloadFileServer) error
	mustEmbedUnimplementedGocalChargerServerServer()
}

// UnimplementedGocalChargerServerServer must be embedded to have forward compatible implementations.
type UnimplementedGocalChargerServerServer struct {
}

func (UnimplementedGocalChargerServerServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGocalChargerServerServer) DownloadFile(*DownloadFileRequest, GocalChargerServer_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedGocalChargerServerServer) mustEmbedUnimplementedGocalChargerServerServer() {}

// UnsafeGocalChargerServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GocalChargerServerServer will
// result in compilation errors.
type UnsafeGocalChargerServerServer interface {
	mustEmbedUnimplementedGocalChargerServerServer()
}

func RegisterGocalChargerServerServer(s grpc.ServiceRegistrar, srv GocalChargerServerServer) {
	s.RegisterService(&GocalChargerServer_ServiceDesc, srv)
}

func _GocalChargerServer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GocalChargerServerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gocalcharger.srv.GocalChargerServer/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GocalChargerServerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GocalChargerServer_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GocalChargerServerServer).DownloadFile(m, &gocalChargerServerDownloadFileServer{stream})
}

type GocalChargerServer_DownloadFileServer interface {
	Send(*DownloadFileReply) error
	grpc.ServerStream
}

type gocalChargerServerDownloadFileServer struct {
	grpc.ServerStream
}

func (x *gocalChargerServerDownloadFileServer) Send(m *DownloadFileReply) error {
	return x.ServerStream.SendMsg(m)
}

// GocalChargerServer_ServiceDesc is the grpc.ServiceDesc for GocalChargerServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GocalChargerServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gocalcharger.srv.GocalChargerServer",
	HandlerType: (*GocalChargerServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GocalChargerServer_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _GocalChargerServer_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gocalcharger.proto",
}
